language: en-US

tone_instructions: >
  Be a mentor. Explain the 'why'. Prioritize critical issues (security, perf) over style. Give code examples. Summarize with a paragraph & action list.

early_access: true        # unlocks experimental features such as autogen unit tests
enable_free_tier: true

reviews:
  profile: assertive       # maximizes nit-picking and depth
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_in_walkthrough: true
  auto_title_placeholder: '@coderabbitai'
  auto_title_instructions: >
    Generate concise, imperative PR titles in sentence case.
  review_status: true
  commit_status: true
  fail_commit_status: true # blocks merge if critical issues detected
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  auto_apply_labels: false
  suggested_reviewers: true
  auto_assign_reviewers: false
  poem: false              # disable fun extras to stay focused
  abort_on_close: true
  disable_cache: false

auto_review:
  enabled: true
  auto_incremental_review: true
  ignore_title_keywords: []
  labels: []
  drafts: false
  base_branches: []

finishing_touches:
  docstrings:
    enabled: true
  unit_tests:
    enabled: true          # requires early_access: true

tools:
  # keep every static-analysis tool enabled (max coverage)
  # … no change needed …

chat:
  auto_reply: true
  integrations:
    jira:
      usage: auto
    linear:
      usage: enabled

knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns: []
  learnings:
    scope: global
  issues:
    scope: auto
  jira:
    usage: auto
    project_keys: []
  linear:
    usage: auto
    team_keys: []
  pull_requests:
    scope: auto

code_generation:
  docstrings:
    language: en-US
    path_instructions: []
  unit_tests:
    path_instructions: []
